### ISSUE TITLE
Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, argon2_hash): symbol not found)

### ISSUE THREAD

**Issue by wal33d006** [tmthecoder/dargon2_flutter#1]

**Comment by tmthecoder** [comment]
Can you provide any stacktrace or log, along with a platform this was tried on?

**Comment by wal33d006** [comment]
I ran it with flutter tests. I think it should work with Flutter tests. I simply copy pasted the whole example code inside a test. Tell me if it's necessary to run it in an app to make it work.

**Comment by tmthecoder** [comment]
Yes, it's necessary to run on an app, either on a simulator or device as the tests do not simulate any operating system's loading of the C library, which gives the issue that the hash method cannot be found as the library is never loaded in the first place due to the tests not being linked to an iOS or Android runtime
